# Generated by Django 5.0.6 on 2024-05-17 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_sections_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('sub_img', models.ImageField(default='static/assets/img/menu/menu-item-1.png', upload_to='static/assets/img/menu/')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sections')),
            ],
        ),
    ]
