# Generated by Django 5.0.6 on 2024-05-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_subsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('loation', models.CharField(max_length=500)),
                ('owner_username', models.CharField(max_length=100)),
                ('place_img', models.ImageField(default='static/assets/img/menu/menu-item-1.png', upload_to='static/assets/img/menu/')),
            ],
        ),
    ]
