# Generated by Django 5.0.6 on 2024-05-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_foodplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodplace',
            old_name='loation',
            new_name='location',
        ),
    ]
