# Generated by Django 5.0.6 on 2024-05-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_loation_foodplace_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplace',
            name='name',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
