# Generated by Django 5.0.6 on 2024-05-18 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_foodplace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='place_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orders.foodplace'),
        ),
    ]
