# Generated by Django 5.0.6 on 2024-05-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_sections_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='section_category',
            field=models.CharField(choices=[('S', 'Snacks'), ('B', 'Beverages'), ('M', 'Main Course')], default='M', max_length=2),
        ),
    ]
