# Generated by Django 5.0.6 on 2024-05-23 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordercontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('subsection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.subsection')),
            ],
        ),
    ]
