# Generated by Django 5.0.6 on 2024-06-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_requestfoodplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfoodplace',
            name='des',
            field=models.CharField(default='hello', max_length=500),
        ),
    ]
