# Generated by Django 5.0.6 on 2024-05-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500)),
                ('price_lower', models.IntegerField(default=0)),
                ('price_higher', models.IntegerField(default=0)),
            ],
        ),
    ]
