# Generated by Django 5.0.6 on 2024-05-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='img',
            field=models.ImageField(default='static\x07ssets\\img\\menu\\menu-item-1.png', upload_to='static/assets/img/menu/'),
        ),
    ]
