# Generated by Django 5.0.6 on 2024-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_log_order_log_data_delete_orderlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestFoodPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('owner_username', models.CharField(max_length=100)),
                ('name', models.CharField(default='Admin', max_length=100)),
            ],
        ),
    ]
